#!/usr/bin/env python

"""
    python-openvas
    ================

    This program interact with openvassd (openvas-scanner) to scan an host.
    It features:
    *email report sent to local smtp server
    *json output sent to local flume server
    *IPv4/IPv6 scans

    Common use:
    -----------
    Run the default scan and receive the report by email by launching:
    python-openvas -v -t 8.8.8.8 -e john@example.com

    Example:
    --------
    python-openvas -v -t 8.8.8.8 -f General, Malware -e john@example.com
    python-openvas -v -t 8.8.8.8 -j -a

    Advices:
    --------
    Please make sure flume channel capacity are big enough to send a big json
    in case there are lot of vulnerabilities.

    main module:
    ------------
    This aims at parsing the CLI args, and runing the different functions.

"""

import sys, signal, re, socket, argparse #General module
import Email, ParseScan, IPTool, OTP, Color #Personnal class

argv=sys.argv[1:] #put the arguments in a string
parser = argparse.ArgumentParser(description="openvas-handler menu")
parser.add_argument('-a', '--all', help='Scan all the families', action='store_true')
parser.add_argument('-f', '--scan-families', metavar="family1, family2", type=str, nargs='?', dest='family', help="Specify families for the families for the scan.", default= ['Finger abuses', 'Malware', 'Windows : Microsoft Bulletins', 'Netware', 'Default Accounts', 'Buffer overflow', 'Policy', 'Useless services', 'Product detection', 'Denial of Service', 'SSL and TLS', 'Gain a shell remotely', 'Web application abuses', 'Service detection', 'RPC', 'Brute force attacks', 'FTP', 'Compliance', 'Settings', 'Windows', 'Nmap NSE', 'Databases', 'Firewalls', 'Credentials', 'IT-Grundschutz', 'SMTP problems', 'Nmap NSE net', 'CISCO', 'Remote file access', 'SNMP', 'Web Servers', 'General', 'Peer-To-Peer File Sharing', 'Privilege escalation', 'Port scanners', 'IT-Grundschutz-12', 'IT-Grundschutz-13', 'IT-Grundschutz-10', 'IT-Grundschutz-11'])
parser.add_argument('-t', '--target', metavar='8.8.8.8 example', type=str ,dest='target', nargs=1, help="IP or domain name of the host to scan")
parser.add_argument('-j', '--json', help='Output the report in JSON', action='store_true')
parser.add_argument('--flume-server', metavar='http://localhost:5140/post', help='Specify flume server adress', nargs=1, type=str,default='http://localhost:5140/post', dest='flume_server') 
parser.add_argument('-l', '--list-families', help="List the families available (ex: Windows, Linux, Cisco, etc)", action='store_true')
parser.add_argument('-e', '--email', metavar="x1@example.com, x2@example.com", type=str, nargs="+", help="Send the report to someone@example.com by email", dest="email")
parser.add_argument('-v', '--verbose', help="Verbose mode. Output the OTP info in the shell.", dest="verbose",default=False,action='store_true')
parser.add_argument('--oid-timeout', type=int, nargs=1, help="Set a timeout for the retrieval of oid. Default is 3s.", dest="oid_timeout",default=3)
parser.add_argument('--scan-timeout', type=int, nargs=1, help="Set a timeout for the scan depending if the firewall is up or down. Default is 300s.", dest="scan_timeout",default=300)
parser.add_argument('--version', action='version', version='%(prog)s 1.0')
parser.add_argument('--initialize-timer', type=int, nargs=1, help="Set a timer to wait for the scanner answer at the beginning. Default is 1s.", dest="initialize_timer",default=1)
parser.add_argument('--from', metavar="x1@example.com", type=str, nargs=1, help="Define the sender of the email report", dest="email_from", default="openvas@cern.ch")
parser.add_argument('--subject', metavar="Openvas Report", type=str, nargs=1, help="Define the subject of the email. Default is Openvas Report", dest="email_subject", default="Openvas Report")

args = parser.parse_args()

if args.target: #Before Giving the ip to the scanner, test if it is a correct ip.
    isIp = IPTool.IPTool(args.target[0])
    ipTarget = isIp.ValidDNIP()

elif args.list_families:
    otpFamilies = OTP.OTP(args.oid_timeout,args.scan_timeout,args.initialize_timer)
    familyDict = otpFamilies.ListFamilies() #retrieve families anyway
    print(familyDict.keys())
    sys.exit(0)

if args.target and ( args.family or args.all): #Check that we have at least an ip and a family to run the scan
    print(Color.BLUE + "Don't forget to deactivate the target firewall !" + Color.END)
    otpScan = OTP.OTP(args.oid_timeout,args.scan_timeout, args.initialize_timer)
    familyDict = otpScan.ListFamilies() #retrieve families anyway
    oidList = otpScan.FamilyToScan(args.all,args.family,familyDict)
    outputScan = otpScan.RunScan(ipTarget,args.verbose,oidList)
    scanReport = ParseScan.ParseScan(outputScan,ipTarget,familyDict) #Parsing the Scan Section
    if args.json: #user asked for json sent to flume
        scanReport.ParserJSON(args.flume_server)
    if args.email: #If the list of destination email has been given, then...
        reportAfterParsing = scanReport.ParserEmail()
        if reportAfterParsing.strip():
            s = Email.Email(reportAfterParsing,args.email,args.email_from,args.email_subject)
            s.sendEmail()
        else:
            print(Color.GREEN + "No Vulnerability detected, then no email sent!" + Color.END)
            sys.exit(0)
else:
    print(Color.RED + "Arguments missing !" + Color.END)
