#!/usr/bin/env python

"""
    openvas-blacklist
    ================

    This program interact with openvassd (openvas-scanner) to scan an host.
    It features:

    Example:
    --------
    openvas-blacklist

"""
import argparse, sys
from lib import __version__, blacklist, oid, otp

parser = argparse.ArgumentParser(description="openvas-blacklsit menu")
parser.add_argument('--info', help="Print information about blacklisted oid", action='store_true')
parser.add_argument('--add',metavar='1.3.6.1.4.1.25623.1.0.80110 1.3.6.1.4.1.25623.1.0.80111', nargs="+", help="Add the oid to blacklist.conf")
parser.add_argument('--remove',metavar='1.3.6.1.4.1.25623.1.0.80110 1.3.6.1.4.1.25623.1.0.80111', nargs="+", help="Remove the oid from blacklist.conf")
parser.add_argument('--version', action='version', version='%(prog)s {}'.format(__version__))
parser.add_argument('-s', '--socket-path', metavar="/var/run/openvassd.sock", type=str, nargs=1, help="Define OpenVAS scanner socket path...", dest="unixsocket_path", default='/var/run/openvassd.sock')

args = parser.parse_args()

blacklist = blacklist.Blacklist()

if args.remove:
    blacklist.RemoveOid(args.remove)
    sys.exit(0)
elif args.add:
    blacklist.AddOid(args.add)
    sys.exit(0)
elif args.info:
    otp = otp.OTP(args.unixsocket_path)
    familyDict = otp.ListFamilies()
    oidinfo = oid.OidInfo(familyDict)
    blacklist.BlacklistInfo(oidinfo)
    sys.exit(0)
